'use strict'

import Template from './Template.js'

export default {
	getBoards: () => [
		{
			name: 'smoothieboard',
            type: 'LPC',
			caption: 'Smoothieboard',
			motorWarningCurrent: 1200,
			motorLimitCurrent: 2000,
			seriesResistor: 4700,
			microstepping: false,
			microsteppingInterpolation: false,
			numDrives: 5,
			heaterPorts: ['bed', 'e0heat', 'e1heat'],
			fanPorts: ['Q4', 'Q8', 'fan0'],
			pwmPorts: ['Q4', 'bed', 'e0heat', 'e1heat', 'Q8', 'fan0'],
			gpioPorts: ['xstop', 'xstopmax', 'ystop', 'ystopmax', 'zstop', 'zstopmax'],
            analogPorts: ['bedtemp', 'e0temp', 'e1temp', 't3'],
            blPorts: [],
			spiCsPorts: [],
			hasEthernet: true,
            hasWiFi: false,
            hasESP: false,
            hasESPUpdate: false,
            hasESPOnboard: false,
            hasSBC: false,
			hasPowerFailureDetection: false,
			hasMotorLoadDetection: false,
			supportsDisplay: true,
			supports12864: true, 
			firmwareStandaloneFile: 'firmware-lpc-esp8266wifi',
            firmwareSBCFile: 'firmware-lpc-sbc',
            firmwareWifiFile: 'DuetWiFiServer-lpc-el.bin',
            requiresBeta: false,
			iapFile: '',
			expansionBoards: [],
			maxExpansionBoards: 0,
            stepperDriver: "A5984",
            stepperDriverTimings: "1.0:1.0:0.4:0.4",
            stepperDriverSmart: false,
            stepperDriver5160: false,
            serialRxPin:'',
            serialTxPin:'',
            espDataReadyPin:'',
            lpcTfrReadyPin:'',
            espResetPin:'',
            lpc: {
                  externalSDCard:{
                      csPin: "0.28",
                      cardDetectPin: "0.27",
                      spiFrequencyHz: 4000000,
                      spiChannel: 0,
                  },
                  internalSDCardSPIFrequencyHz: 25000000,
                  lcd:{
                      lcdCSPin:       "0.16",
                      lcdBeepPin:     "1.31",
                      encoderPinA:    "3.25",
                      encoderPinB:    "3.26",
                      encoderPinSw:   "1.30",
                      lcdDCPin:       "NoPin",
                      panelButtonPin: "2.11",
                      spiChannel: 0,
                  },
                  diagnosticPin: "1.18",
            },
            drives: [
				{
                    diag: "NoPin",
                }
            ],
            auxRX:'',
            auxTX:'',
            serialAmount:'1',
            wifi8266CSPin: 'NoPin'

		},
        {
            name: 'biquskr_1.1',
            type: 'LPC',
            caption: 'SKR v1.1',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: false,
            microsteppingInterpolation: false,
            numDrives: 5,
            heaterPorts: ['bed', 'e0heat', 'e1heat'],
            fanPorts: ['fan0', 'e1heat'],
            pwmPorts: ['bed', 'e0heat', 'e1heat', 'fan0'],
            gpioPorts: ['xstop', 'xstopmax', 'ystop', 'ystopmax', 'zstop', 'zstopmax'],
            analogPorts: ['bedtemp', 'e0temp', 'e1temp'],
            blPorts: [],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: true,
            hasESPUpdate: false,
            hasESPOnboard: false,
            hasSBC: true,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: false,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-lpc-esp8266wifi',
            firmwareSBCFile: 'firmware-lpc-sbc',
            firmwareWifiFile: 'DuetWiFiServer-lpc-el.bin',
            requiresBeta: false,
            iapFile: '',
            expansionBoards: [],
            maxExpansionBoards: 0,
            stepperDriver: "", // no built in drivers.
            stepperDriverTimings: "",
            stepperDriverSmart: false,
            stepperDriver5160: false,
            serialRxPin:'0.3',
            serialTxPin:'0.2',
            espDataReadyPin:'0.28',
            lpcTfrReadyPin:'1.30',
            espResetPin:'1.31',
            lpc: {
                externalSDCard:{
                    csPin: "1.23",
                    cardDetectPin: "1.31",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                },
                internalSDCardSPIFrequencyHz: 25000000,
                softwareSPI:{
                    pins: ["1.20", "NoPin", "1.18"],
                },
                lcd:{
                    lcdCSPin:       "0.16",
                    lcdBeepPin:     "1.30",
                    encoderPinA:    "3.26",
                    encoderPinB:    "3.25",
                    encoderPinSw:   "2.11",
                    lcdDCPin:       "0.18",
                    panelButtonPin: "NoPin",
                    spiChannel: 2, //Software SPI
                },
                diagnosticPin: "NoPin",
            },
            drives: [
                {
                diag: "NoPin",
                }
            ],
            auxRX:'0.3',
            auxTX:'0.2',
            serialAmount:'1',
            wifi8266CSPin: 'NoPin'
        },
        {
            name: 'biquskr_1.3',
            type: 'LPC',
            caption: 'SKR v1.3',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: true,
            microsteppingInterpolation: true,
            numDrives: 5,
            heaterPorts: ['bed', 'e0heat', 'e1heat'],
            fanPorts: ['fan0', 'e1heat'],
            pwmPorts: ['bed', 'e0heat', 'e1heat', 'fan0'],
            gpioPorts: ['xstop', 'xstopmax', 'ystop', 'ystopmax', 'zstop', 'zstopmax'],
            analogPorts: ['bedtemp', 'e0temp', 'e1temp'],
            blPorts: ['servo0'],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: true,
            hasESPUpdate: false,
            hasESPOnboard: false,
            hasSBC: true,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: true,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-lpc-esp8266wifi',
            firmwareSBCFile: 'firmware-lpc-sbc',
            firmwareWifiFile: 'DuetWiFiServer-lpc-el.bin',
            requiresBeta: false,
            iapFile: '',
            expansionBoards: ['BTT EXP-MOT'],
            maxExpansionBoards: 1,
            stepperDriver: "", // no built in drivers.
            stepperDriverTimings: "",
            stepperDriverSmart: true,
            stepperDriver5160: false,
            serialRxPin:'0.3',
            serialTxPin:'0.2',
            espDataReadyPin:'0.28',
            lpcTfrReadyPin:'1.30',
            espResetPin:'1.31',
            lpc: {
                externalSDCard:{
                    csPin: "0.16",
                    cardDetectPin: "1.31",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                },
                internalSDCardSPIFrequencyHz: 25000000,
                softwareSPI:{
                    pins: ["1.20", "NoPin", "1.18"],
                },
                lcd:{
                    lcdCSPin:       "1.19",
                    lcdBeepPin:     "1.30",
                    encoderPinA:    "3.26",
                    encoderPinB:    "3.25",
                    encoderPinSw:   "0.28",
                    lcdDCPin:       "NoPin",
                    panelButtonPin: "NoPin",
                    spiChannel: 2, //Software SPI
                },
                diagnosticPin: "NoPin",
            },
            drives: [
				{
                    diag: "1.29",
                },
                {
                    diag: "1.28",
                },
                {
                    diag: "1.27",
                },
                {
                    diag: "1.26",
                },
                {
                    diag: "1.25",
                }
            ],
            auxRX:'0.3',
            auxTX:'0.2',
            serialAmount:'1',
            wifi8266CSPin: 'NoPin'
        },
	    {
            name: 'biquskr_1.4',
            type: 'LPC',
            caption: 'SKR v1.4',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: true,
            microsteppingInterpolation: true,
            numDrives: 5,
            heaterPorts: ['bed', 'e0heat', 'e1heat'],
            fanPorts: ['fan0', 'e1heat'],
            pwmPorts: ['bed', 'e0heat', 'e1heat', 'fan0'],
            gpioPorts: ['xstop', 'ystop', 'zstop', 'e0stop', 'e1stop', 'probe', 'pwrstop'],
            analogPorts: ['bedtemp', 'e0temp', 'e1temp'],
            blPorts: ['servo0'],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: true,
            hasESPUpdate: false,
            hasESPOnboard: false,
            hasSBC: true,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: true,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-lpc-esp8266wifi',
            firmwareSBCFile: 'firmware-lpc-sbc',
            firmwareWifiFile: 'DuetWiFiServer-lpc-el.bin',
            requiresBeta: false,
            iapFile: '',
            expansionBoards: ['BTT EXP-MOT'],
            maxExpansionBoards: 1,
            stepperDriver: "", // no built in drivers.
            stepperDriverTimings: "",
            stepperDriverSmart: true,
            stepperDriver5160: false,
            serialRxPin:'4.29',
            serialTxPin:'4.28',
            espDataReadyPin:'0.28',
            lpcTfrReadyPin:'1.30',
            espResetPin:'1.31',
            lpc: {
                externalSDCard:{
                    csPin: "0.16",
                    cardDetectPin: "1.31",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                },
                internalSDCardSPIFrequencyHz: 25000000,
                softwareSPI:{
                    pins: ["1.20", "NoPin", "1.18"],
                },
                lcd:{
                    lcdCSPin:       "1.19",
                    lcdBeepPin:     "1.30",
                    encoderPinA:    "3.26",
                    encoderPinB:    "3.25",
                    encoderPinSw:   "0.28",
                    lcdDCPin:       "NoPin",
                    panelButtonPin: "NoPin",
                    spiChannel: 2, //Software SPI
                },
                diagnosticPin: "NoPin",
            },
            drives: [
				{
                    diag: "1.29",
                },
                {
                    diag: "1.28",
                },
                {
                    diag: "1.27",
                },
                {
                    diag: "1.26",
                },
                {
                    diag: "1.25",
                }
            ],
            auxRX:'0.3',
            auxTX:'0.2',
            serialAmount:'2',
            wifi8266CSPin: 'NoPin'
        },
	    {
            name: 'azsmz',
            type: 'LPC',
            caption: 'Azsmz Mini',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: false,
            microsteppingInterpolation: false,
            numDrives: 5,
            heaterPorts: ['bed', 'e0heat', 'e1heat'],
            fanPorts: ['fan0', 'e1heat'],
            pwmPorts: ['bed', 'e0heat', 'e1heat', 'fan0'],
            gpioPorts: ['xstop', 'ystop', 'zstop', 'e0stop', 'e1stop', 'probe', 'servo0'],
            analogPorts: ['bedtemp', 'e0temp', 'e1temp'],
            blPorts: [],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: false,
            hasESPUpdate: false,
            hasESPOnboard: false,
            hasSBC: false,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: false,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-lpc-esp8266wifi',
            firmwareSBCFile: 'firmware-lpc-sbc',
            firmwareWifiFile: 'DuetWiFiServer-lpc-el.bin',
            requiresBeta: false,
            iapFile: '',
            expansionBoards: [],
            maxExpansionBoards: 0,
            stepperDriver: "", // no built in drivers.
            stepperDriverTimings: "",
            stepperDriverSmart: false,
            stepperDriver5160: false,
            serialRxPin:'0.3',
            serialTxPin:'0.2',
            espDataReadyPin:'0.28',
            lpcTfrReadyPin:'1.30',
            espResetPin:'1.31',
            lpc: {
                externalSDCard:{
                    csPin: "0.16",
                    cardDetectPin: "3.25",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                },
                internalSDCardSPIFrequencyHz: 25000000,
                softwareSPI:{
                    pins: ["NoPin", "NoPin", "NoPin"],
                },
                lcd:{
                    lcdCSPin:       "1.22",
                    lcdBeepPin:     "1.30",
                    encoderPinA:    "4.28",
                    encoderPinB:    "1.27",
                    encoderPinSw:   "3.26",
                    lcdDCPin:       "2.6",
                    panelButtonPin: "NoPin",
                    spiChannel: 2, //Software SPI
                },
                diagnosticPin: "1.18",
            },
            drives: [
				{
                    diag: "NoPin",
                }
            ],
            auxRX:'',
            auxTX:'',
            serialAmount:'1',
            wifi8266CSPin: 'NoPin'
        },
	    {
            name: 'azteegX5_1.1',
            type: 'LPC',
            caption: 'Azteeg X5 Mini v1.1',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: false,
            microsteppingInterpolation: false,
            numDrives: 4,
            heaterPorts: ['bed', 'e0heat', 'e1heat'],
            fanPorts: ['fan0', 'e1heat'],
            pwmPorts: ['bed', 'e0heat', 'e1heat', 'fan0'],
            gpioPorts: ['xstop', 'ystop', 'zstop', 'e0stop'],
            analogPorts: ['bedtemp', 'e0temp'],
            blPorts: [],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: false,
            hasESPUpdate: false,
            hasESPOnboard: false,
            hasSBC: false,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: false,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-lpc-esp8266wifi',
            firmwareSBCFile: 'firmware-lpc-sbc',
            firmwareWifiFile: 'DuetWiFiServer-lpc-el.bin',
            requiresBeta: false,
            iapFile: '',
            expansionBoards: [],
            maxExpansionBoards: 0,
            stepperDriver: "", // no built in drivers.
            stepperDriverTimings: "",
            stepperDriverSmart: false,
            stepperDriver5160: false,
            serialRxPin:'',
            serialTxPin:'',
            espDataReadyPin:'',
            lpcTfrReadyPin:'',
            espResetPin:'',
            lpc: {
                externalSDCard:{
                    csPin: "1.23",
                    cardDetectPin: "1.31",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                },
                internalSDCardSPIFrequencyHz: 25000000,
                softwareSPI:{
                    pins: ["NoPin", "NoPin", "NoPin"],
                },
                lcd:{
                    lcdCSPin:       "0.16",
                    lcdBeepPin:     "0.25",
                    encoderPinA:    "3.25",
                    encoderPinB:    "3.26",
                    encoderPinSw:   "2.11",
                    lcdDCPin:       "2.6",
                    panelButtonPin: "1.22",
                    spiChannel: 2, //Software SPI
                },
                diagnosticPin: "4.28",
            },
            drives: [
				{
                    diag: "NoPin",
                }
            ],
            auxRX:'',
            auxTX:'',
            serialAmount:'1',
            wifi8266CSPin: 'NoPin'
        },
        {
            name: 'rearm',
            type: 'LPC',
            caption: 'ReARM',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: false,
            microsteppingInterpolation: false,
            numDrives: 5,
            heaterPorts: ['bed', 'e0heat', 'e1heat'],
            fanPorts: ['e1heat'],
            pwmPorts: ['bed', 'e0heat', 'e1heat', 'Servo0', 'Servo1', 'Servo3'],
            gpioPorts: ['xstop', 'xstopmax', 'ystop', 'ystopmax', 'zstop', 'zstopmax'],
            analogPorts: ['bedtemp', 'e0temp', 'e1temp'],
            blPorts: [],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: false,
            hasESPUpdate: false,
            hasESPOnboard: false,
            hasSBC: false,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: false,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-lpc-esp8266wifi',
            firmwareSBCFile: 'firmware-lpc-sbc',
            firmwareWifiFile: 'DuetWiFiServer-lpc-el.bin',
            requiresBeta: false,
            iapFile: '',
            expansionBoards: [],
            maxExpansionBoards: 0,
            stepperDriver: "", // no built in drivers.
            stepperDriverTimings: "",
            stepperDriverSmart: false,
            stepperDriver5160: false,
            serialRxPin:'',
            serialTxPin:'',
            espDataReadyPin:'',
            lpcTfrReadyPin:'',
            espResetPin:'',
            lpc: {
                externalSDCard:{
                    csPin: "1.23",
                    cardDetectPin: "1.31",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                },
                internalSDCardSPIFrequencyHz: 25000000,
                lcd:{
                    lcdCSPin:       "0.16",
                    lcdBeepPin:     "1.30",
                    encoderPinA:    "3.25",
                    encoderPinB:    "3.26",
                    encoderPinSw:   "2.11",
                    lcdDCPin:       "2.6",
                    panelButtonPin: "1.22",
                    spiChannel: 0,
                },
                diagnosticPin: "4.28",
            },
            drives: [
				{
                    diag: "NoPin",
                }
            ],
            auxRX:'',
            auxTX:'',
            serialAmount:'1',
            wifi8266CSPin: 'NoPin'
        },
        {
            name: 'mkssbase_1.3',
            type: 'LPC',
            caption: 'MKS Sbase 1.3',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: false,
            microsteppingInterpolation: false,
            numDrives: 5,
            heaterPorts: ['BED', 'E1', 'E2'],
            fanPorts: ['FAN', 'E2'],
            pwmPorts: ['BED', 'E1', 'E2', 'FAN'],
            gpioPorts: ['XMin', 'YMin', 'ZMin', 'XMax', 'YMax', 'ZMax'],
            analogPorts: ['TH1', 'TH2', 'TH3', 'TH4'],
            blPorts: [],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: false,
            hasESPUpdate: false,
            hasESPOnboard: false,
            hasSBC: false,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: false,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-lpc-esp8266wifi',
            firmwareSBCFile: 'firmware-lpc-sbc',
            firmwareWifiFile: 'DuetWiFiServer-lpc-el.bin',
            requiresBeta: false,
            iapFile: '',
            expansionBoards: [],
            maxExpansionBoards: 0,
            stepperDriver: "DRV8825",
            stepperDriverTimings: "1.9:1.9:0.65:0.65",
            stepperDriverSmart: false,
            stepperDriver5160: false,
            serialRxPin:'0.3',
            serialTxPin:'0.2',
            espDataReadyPin:'',
            lpcTfrReadyPin:'',
            espResetPin:'',
            lpc: {
                externalSDCard:{
                    csPin: "0.28",
                    cardDetectPin: "0.27",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                    },
                internalSDCardSPIFrequencyHz: 25000000,
                lcd:{
                    lcdCSPin:       "0.16",
                    lcdBeepPin:     "1.31",
                    encoderPinA:    "3.25",
                    encoderPinB:    "3.26",
                    encoderPinSw:   "1.30",
                    lcdDCPin:       "NoPin",
                    panelButtonPin: "2.11",
                    spiChannel: 0,
                },
                diagnosticPin: "1.18",
            },
            drives: [
				{
                    diag: "NoPin",
                }
            ],
            auxRX:'0.3',
            auxTX:'0.2',
            serialAmount:'1',
            wifi8266CSPin: 'NoPin'
        },
        {
            name: 'mkssgenl_1.0',
            type: 'LPC',
            caption: 'MKS SGen L v1.0',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: true,
            microsteppingInterpolation: true,
            numDrives: 5,
            heaterPorts: ['bed', 'e0heat', 'e1heat'],
            fanPorts: ['fan0', 'e1heat'],
            pwmPorts: ['bed', 'e0heat', 'e1heat', 'fan0'],
            gpioPorts: ['xstop', 'xstopmax', 'ystop', 'ystopmax', 'zstop', 'zstopmax'],
            analogPorts: ['bedtemp', 'e0temp', 'e1temp'],
            blPorts: ['servo0'],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: true,
            hasESPUpdate: false,
            hasESPOnboard: false,
            hasSBC: true,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: true,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-lpc-esp8266wifi',
            firmwareSBCFile: 'firmware-lpc-sbc',
            firmwareWifiFile: 'DuetWiFiServer-lpc-el.bin',
            requiresBeta: false,
            iapFile: '',
            expansionBoards: [],
            maxExpansionBoards: 0,
            stepperDriver: "",
            stepperDriverTimings: "",
            stepperDriverSmart: true,
            stepperDriver5160: false,
            serialRxPin:'0.3',
            serialTxPin:'0.2',
            espDataReadyPin:'0.28',
            lpcTfrReadyPin:'1.30',
            espResetPin:'1.31',
            lpc: {
                externalSDCard:{
                    csPin: "0.16",
                    cardDetectPin: "1.31",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                    },
                internalSDCardSPIFrequencyHz: 25000000,
                softwareSPI:{
                    pins: ["1.20", "NoPin", "1.18"],
                    },
                lcd:{
                    lcdCSPin:       "1.19",
                    lcdBeepPin:     "1.30",
                    encoderPinA:    "3.26",
                    encoderPinB:    "3.25",
                    encoderPinSw:   "0.28",
                    lcdDCPin:       "NoPin",
                    panelButtonPin: "NoPin",
                    spiChannel: 2, //Software SPI
                },
                diagnosticPin: "1.18",
            },
            drives: [
                {
                diag: "1.29",
                },
                {
                diag: "1.27",
                },
                {
                diag: "1.25",
                },
                {
                diag: "1.28",
                },
                {
                diag: "1.26",
                }
            ],
            auxRX:'0.3',
            auxTX:'0.2',
            serialAmount:'1',
            wifi8266CSPin: 'NoPin'
        },
        {
            name: 'mkssgenl_2.0',
            type: 'LPC',
            caption: 'MKS SGen L v2.0',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: true,
            microsteppingInterpolation: true,
            numDrives: 5,
            heaterPorts: ['bed', 'e0heat', 'e1heat'],
            fanPorts: ['fan0','fan1', 'e1heat'],
            pwmPorts: ['bed', 'e0heat', 'e1heat', 'fan0','fan1'],
            gpioPorts: ['xstop', 'xstopmax', 'ystop', 'ystopmax', 'zstop', 'zstopmax'],
            analogPorts: ['bedtemp', 'e0temp', 'e1temp'],
            blPorts: ['servo0','servo1'],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: true,
            hasESPUpdate: false,
            hasESPOnboard: false,
            hasSBC: true,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: true,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-lpc-esp8266wifi',
            firmwareSBCFile: 'firmware-lpc-sbc',
            firmwareWifiFile: 'DuetWiFiServer-lpc-el.bin',
            requiresBeta: false,
            iapFile: '',
            expansionBoards: [],
            maxExpansionBoards: 0,
            stepperDriver: "",
            stepperDriverTimings: "",
            stepperDriverSmart: true,
            stepperDriver5160: false,
            serialRxPin:'4.29',
            serialTxPin:'4.28',
            espDataReadyPin:'0.28',
            lpcTfrReadyPin:'1.30',
            espResetPin:'1.31',
            lpc: {
                externalSDCard:{
                    csPin: "0.16",
                    cardDetectPin: "1.31",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                },
                internalSDCardSPIFrequencyHz: 25000000,
                softwareSPI:{
                    pins: ["1.20", "NoPin", "1.18"],
                },
                lcd:{
                    lcdCSPin:       "1.19",
                    lcdBeepPin:     "1.30",
                    encoderPinA:    "3.26",
                    encoderPinB:    "3.25",
                    encoderPinSw:   "0.28",
                    lcdDCPin:       "NoPin",
                    panelButtonPin: "NoPin",
                    spiChannel: 2, //Software SPI
                },
                diagnosticPin: "1.18",
            },
            drives: [
                {
                diag: "1.29",
                },
                {
                diag: "1.27",
                },
                {
                diag: "1.25",
                },
                {
                diag: "1.28",
                },
                {
                diag: "1.26",
                }
            ],
            auxRX:'0.3',
            auxTX:'0.2',
            serialAmount:'2',
            wifi8266CSPin: 'NoPin'
        },
        {
            name: 'biquskr_e3t',
            type: 'LPC',
            caption: 'SKR E3 Turbo',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: true,
            microsteppingInterpolation: true,
            numDrives: 5,
            heaterPorts: ['bed', 'e0heat', 'e1heat'],
            fanPorts: ['fan0','fan1', 'e1heat'],
            pwmPorts: ['bed', 'e0heat', 'e1heat', 'fan0','fan1'],
            gpioPorts: ['xstop', 'ystop', 'zstop', 'e0stop','e1stop','probe0','probe1','ptdet'],
            analogPorts: ['bedtemp', 'e0temp', 'e1temp'],
            blPorts: ['servo0','servo1'],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: true,
            hasESPUpdate: false,
            hasESPOnboard: false,
            hasSBC: true,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: true,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-lpc-esp8266wifi',
            firmwareSBCFile: 'firmware-lpc-sbc',
            firmwareWifiFile: 'DuetWiFiServer-lpc-el.bin',
            requiresBeta: false,
            iapFile: '',
            expansionBoards: [],
            maxExpansionBoards: 0,
            stepperDriver: "",
            stepperDriverTimings: "",
            stepperDriverSmart: true,
            stepperDriver5160: false,
            serialRxPin:'0.3',
            serialTxPin:'0.2',
            espDataReadyPin:'0.19',
            lpcTfrReadyPin:'0.20',
            espResetPin:'2.8',
            lpc: {
                externalSDCard:{
                    csPin: "0.16",
                    cardDetectPin: "1.31",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                },
                internalSDCardSPIFrequencyHz: 25000000,
                softwareSPI:{
                    pins: ["1.20", "NoPin", "1.18"],
                },
                lcd:{
                    lcdCSPin:       "1.19",
                    lcdBeepPin:     "1.30",
                    encoderPinA:    "3.26",
                    encoderPinB:    "3.25",
                    encoderPinSw:   "0.28",
                    lcdDCPin:       "NoPin",
                    panelButtonPin: "NoPin",
                    spiChannel: 2, //Software SPI
                },
                diagnosticPin: "NoPin",
            },
            drives: [
                {
                diag: "1.29",
                },
                {
                diag: "1.28",
                },
                {
                diag: "1.27",
                },
                {
                diag: "1.26",
                },
                {
                diag: "1.25",
                }
            ],
            auxRX:'0.3',
            auxTX:'0.2',
            serialAmount:'1',
            wifi8266CSPin: 'NoPin'
        },
        {
            name: 'biquskrpro_1.1',
            type: 'STM32F4',
            caption: 'SKR Pro',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: true,
            microsteppingInterpolation: true,
            numDrives: 6,
            heaterPorts: ['bed', 'e0heat', 'e1heat','e2heat'],
            fanPorts: ['fan0','fan1','fan2'],
            pwmPorts: ['bed', 'e0heat', 'e1heat','e2heat','fan0','fan1','fan2'],
            gpioPorts: ['xstop','ystop','zstop', 'e0stop','e1stop','e2stop','probe'],
            analogPorts: ['bedtemp', 'e0temp', 'e1temp','e2temp'],
            blPorts: ['servo0'],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: true,
            hasESPUpdate: false,
            hasESPOnboard: false,
            hasSBC: true,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: true,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-stm32f4-esp8266wifi',
            firmwareSBCFile: 'firmware-stm32f4-sbc',
            firmwareWifiFile: 'DuetWiFiServer-stm32f4.bin',
            requiresBeta: false,
            iapFile: '',
            expansionBoards: ['BTT EXP-MOT'],
            maxExpansionBoards: 1,
            stepperDriver: "",
            stepperDriverTimings: "",
            stepperDriverSmart: true,
            stepperDriver5160: true,
            serialRxPin:'PD.9',
            serialTxPin:'PD.8',
            espDataReadyPin:'PA.8',
            lpcTfrReadyPin:'PG.4',
            espResetPin:'PF.12',
            lpc: {
                externalSDCard:{
                    csPin: "NoPin",
                    cardDetectPin: "NoPin",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                },
                internalSDCardSPIFrequencyHz: 25000000,
                softwareSPI:{
                    pins: ["NoPin", "NoPin", "NoPin"],
                },
                lcd:{
                    lcdCSPin:       "NoPin",
                    lcdBeepPin:     "NoPin",
                    encoderPinA:    "NoPin",
                    encoderPinB:    "NoPin",
                    encoderPinSw:   "NoPin",
                    lcdDCPin:       "NoPin",
                    panelButtonPin: "NoPin",
                    spiChannel: 2, //Software SPI
                },
                diagnosticPin: "PA.7",
            },
            drives: [
                {
                diag: "PB.10",
                },
                {
                diag: "PE.12",
                },
                {
                diag: "PG.8",
                },
                {
                diag: "PE.15",
                },
                {
                diag: "PE.10",
                },
                {
                diag: "PG.5",
                }
            ],
            auxRX:'PA.10',
            auxTX:'PA.9',
            serialAmount:'3',
            wifi8266CSPin: 'NoPin'
        },
        {
            name: 'biqugtr_1.0',
            type: 'STM32F4',
            caption: 'SKR GTR v1.0',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: true,
            microsteppingInterpolation: true,
            numDrives: 6,
            heaterPorts: ['bed', 'e0heat', 'e1heat','e2heat',],
            fanPorts: ['fan0','fan1','fan2'],
            pwmPorts: ['bed', 'e0heat', 'e1heat','e2heat','fan0','fan1','fan2'],
            gpioPorts: ['xstop','ystop','zstop', 'e0stop','e1stop','e2stop','probe'],
            analogPorts: ['bedtemp', 'e0temp', 'e1temp','e2temp'],
            blPorts: ['servo0'],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: true,
            hasESPUpdate: false,
            hasESPOnboard: false,
            hasSBC: true,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: true,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-stm32f4-esp8266wifi',
            firmwareSBCFile: 'firmware-stm32f4-sbc',
            firmwareWifiFile: 'DuetWiFiServer-stm32f4.bin',
            requiresBeta: false,
            iapFile: '',
            expansionBoards: ['M5'],
            maxExpansionBoards: 1,
            stepperDriver: "",
            stepperDriverTimings: "",
            stepperDriverSmart: true,
            stepperDriver5160: true,
            serialRxPin:'P.C7',
            serialTxPin:'P.C6',
            espDataReadyPin:'PA.15',
            lpcTfrReadyPin:'PC.11',
            espResetPin:'PB.10',
            lpc: {
                externalSDCard:{
                    csPin: "NoPin",
                    cardDetectPin: "NoPin",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                },
                internalSDCardSPIFrequencyHz: 25000000,
                softwareSPI:{
                    pins: ["NoPin", "NoPin", "NoPin"],
                },
                lcd:{
                    lcdCSPin:       "NoPin",
                    lcdBeepPin:     "NoPin",
                    encoderPinA:    "NoPin",
                    encoderPinB:    "NoPin",
                    encoderPinSw:   "NoPin",
                    lcdDCPin:       "NoPin",
                    panelButtonPin: "NoPin",
                    spiChannel: 2, //Software SPI
                },
                diagnosticPin: "PA.0",
            },
            drives: [
                {
                diag: "PF.2",
                },
                {
                diag: "PC.13",
                },
                {
                diag: "PE.0",
                },
                {
                diag: "PG.14",
                },
                {
                diag: "PG.9",
                },
                {
                diag: "PD.3",
                },
                {
                diag: "PI.4",
                },
                {
                diag: "PF.4",
                },
                {
                diag: "PF.6",
                },
                {
                diag: "PI.7",
                },
                {
                diag: "PF.12",
                }
            ],
            auxRX:'PD.9',
            auxTX:'PD.8',
            serialAmount:'3',
            wifi8266CSPin: 'NoPin'
        },
        {
            name: 'fly_cdy',
            type: 'LPC',
            caption: 'Fly-CDY',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: true,
            microsteppingInterpolation: true,
            numDrives: 6,
            heaterPorts: ['bed', 'e0heat', 'e1heat','e2heat'],
            fanPorts: ['fan0','fan1','fan2'],
            pwmPorts: ['bed', 'e0heat', 'e1heat','e2heat','fan0','fan1','fan2'],
            gpioPorts: ['xstop','ystop','zstop', 'xstopmax','ystopmax','zstopmax'],
            analogPorts: ['bedtemp', 'e0temp', 'e1temp','e2temp'],
            blPorts: ['servo0'],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: true,
            hasESPUpdate: true,
            hasESPOnboard: true,
            hasSBC: false,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: true,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-lpc-esp8266wifi',
            firmwareSBCFile: 'firmware-lpc-sbc',
            firmwareWifiFile: 'DuetWiFiServer-lpc-el.bin',
            requiresBeta: false,
            iapFile: '',
            expansionBoards: [],
            maxExpansionBoards: 0,
            stepperDriver: "",
            stepperDriverTimings: "",
            stepperDriverSmart: true,
            stepperDriver5160: false,
            serialRxPin:'0.1',
            serialTxPin:'0.0',
            espDataReadyPin:'0.28',
            lpcTfrReadyPin:'2.7',
            espResetPin:'2.6',
            lpc: {
                externalSDCard:{
                    csPin: "NoPin",
                    cardDetectPin: "NoPin",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                },
                internalSDCardSPIFrequencyHz: 25000000,
                softwareSPI:{
                    pins: ["NoPin", "NoPin", "NoPin"],
                },
                lcd:{
                    lcdCSPin:       "NoPin",
                    lcdBeepPin:     "NoPin",
                    encoderPinA:    "NoPin",
                    encoderPinB:    "NoPin",
                    encoderPinSw:   "NoPin",
                    lcdDCPin:       "NoPin",
                    panelButtonPin: "NoPin",
                    spiChannel: 2, //Software SPI
                },
                diagnosticPin: "NoPin",
            },
            drives: [
                {
                diag: "1.29",
                },
                {
                diag: "1.28",
                },
                {
                diag: "1.27",
                },
                {
                diag: "1.25",
                },
                {
                diag: "1.22",
                },
                {
                diag: "1.19",
                }
            ],
            auxRX:'0.3',
            auxTX:'0.2',
            serialAmount:'2',
            wifi8266CSPin: 'NoPin'
        },
        {
            name: 'fly_F407ZG',
            type: 'STM32F4',
            caption: 'Fly-F407ZG',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: true,
            microsteppingInterpolation: true,
            numDrives: 9,
            heaterPorts: ['bed', 'e0heat', 'e1heat','e2heat','e3heat','e4heat','e5heat'],
            fanPorts: ['fan0','fan1','fan2','fan3','fan4','fan5'],
            pwmPorts: ['bed', 'e0heat', 'e1heat','e2heat','e3heat','e4heat','e5heat','fan0','fan1','fan2','fan3','fan4','fan5'],
            gpioPorts: ['xstop','ystop','zstop', 'xstopmax','ystopmax','zstopmax','Z3','DLJC'],
            analogPorts: ['bedtemp', 'e0temp', 'e1temp','e2temp','e3temp','e4temp','e5temp'],
            blPorts: ['servo0'],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: true,
            hasESPUpdate: false,
            hasESPOnboard: false,
            hasSBC: true,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: false,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-stm32f4-esp8266wifi',
            firmwareSBCFile: 'firmware-stm32f4-sbc',
            firmwareWifiFile: 'DuetWiFiServer-stm32f4.bin',
            requiresBeta: false,
            iapFile: '',
            expansionBoards: [],
            maxExpansionBoards: 0,
            stepperDriver: "",
            stepperDriverTimings: "",
            stepperDriverSmart: true,
            stepperDriver5160: false,
            serialRxPin:'A.10',
            serialTxPin:'A.9',
            espDataReadyPin:'E.15',
            lpcTfrReadyPin:'B.10',
            espResetPin:'B.2',
            lpc: {
                externalSDCard:{
                    csPin: "NoPin",
                    cardDetectPin: "NoPin",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                },
                internalSDCardSPIFrequencyHz: 25000000,
                softwareSPI:{
                    pins: ["NoPin", "NoPin", "NoPin"],
                },
                lcd:{
                    lcdCSPin:       "NoPin",
                    lcdBeepPin:     "NoPin",
                    encoderPinA:    "NoPin",
                    encoderPinB:    "NoPin",
                    encoderPinSw:   "NoPin",
                    lcdDCPin:       "NoPin",
                    panelButtonPin: "NoPin",
                    spiChannel: 2, //Software SPI
                },
                diagnosticPin: "NoPin",
            },
            drives: [
                {
                diag: "NoPin",
                },
                {
                diag: "NoPin",
                },
                {
                diag: "NoPin",
                },
                {
                diag: "NoPin",
                },
                {
                diag: "NoPin",
                },
                {
                diag: "NoPin",
                },
                {
                diag: "NoPin",
                },
                {
                diag: "NoPin",
                },
                {
                diag: "NoPin",
                }
            ],
            auxRX:'PA.10',
            auxTX:'PA.9',
            serialAmount:'1',
            wifi8266CSPin: 'PF.11'
        },
        {
            name: 'fly_E3',
            type: 'STM32F4',
            caption: 'Fly-E3',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: true,
            microsteppingInterpolation: true,
            numDrives: 4,
            heaterPorts: ['bed', 'e0heat'],
            fanPorts: ['fan0','fan1'],
            pwmPorts: ['bed', 'e0heat','fan0','fan1'],
            gpioPorts: ['xstop','ystop','zstop', 'probe'],
            analogPorts: ['bedtemp', 'e0temp'],
            blPorts: ['servo0'],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: true,
            hasESPUpdate: true,
            hasESPOnboard: true,
            hasSBC: false,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: true,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-stm32f4-esp8266wifi',
            firmwareSBCFile: 'firmware-stm32f4-sbc',
            firmwareWifiFile: 'DuetWiFiServer-stm32f4.bin',
            requiresBeta: false,
            iapFile: '',
            expansionBoards: [],
            maxExpansionBoards: 0,
            stepperDriver: "",
            stepperDriverTimings: "",
            stepperDriverSmart: true,
            stepperDriver5160: true,
            serialRxPin:'PD.9',
            serialTxPin:'PD.8',
            espDataReadyPin:'PE.13',
            lpcTfrReadyPin:'PE.14',
            espResetPin:'PE.15',
            lpc: {
                externalSDCard:{
                    csPin: "NoPin",
                    cardDetectPin: "NoPin",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                },
                internalSDCardSPIFrequencyHz: 25000000,
                softwareSPI:{
                    pins: ["NoPin", "NoPin", "NoPin"],
                },
                lcd:{
                    lcdCSPin:       "NoPin",
                    lcdBeepPin:     "NoPin",
                    encoderPinA:    "NoPin",
                    encoderPinB:    "NoPin",
                    encoderPinSw:   "NoPin",
                    lcdDCPin:       "NoPin",
                    panelButtonPin: "NoPin",
                    spiChannel: 2, //Software SPI
                },
                diagnosticPin: "PA.8",
            },
            drives: [
                {
                    diag: "PE.6",
                },
                {
                    diag: "PE.2",
                },
                {
                    diag: "PD.5",
                },
                {
                    diag: "PD.7",
                }
            ],
            auxRX:'PA.10',
            auxTX:'PA.9',
            serialAmount:'2',
            wifi8266CSPin: 'NoPin'
        },
        {
            name: 'fly_cdyv2',
            type: 'STM32F4',
            caption: 'Fly-CDYv2',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: true,
            microsteppingInterpolation: true,
            numDrives: 6,
            heaterPorts: ['bed', 'e0heat', 'e1heat', 'e2heat'],
            fanPorts: ['fan0','fan1','fan2','laser'],
            pwmPorts: ['bed', 'e0heat', 'e1heat', 'e2heat','fan0','fan1','fan2','laser'],
            gpioPorts: ['xstop','xstopmax','ystop',,'ystopmax','zstop','zstopmax', 'probe'],
            analogPorts: ['bedtemp', 'e0temp','e1temp','e2temp'],
            blPorts: ['servo0'],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: true,
            hasESPUpdate: true,
            hasESPOnboard: true,
            hasSBC: false,
            hasPowerFailureDetection: true,
            hasMotorLoadDetection: true,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-stm32f4-esp8266wifi',
            firmwareSBCFile: 'firmware-stm32f4-sbc',
            firmwareWifiFile: 'DuetWiFiServer-stm32f4.bin',
            requiresBeta: false,
            iapFile: '',
            expansionBoards: [],
            maxExpansionBoards: 0,
            stepperDriver: "",
            stepperDriverTimings: "",
            stepperDriverSmart: true,
            stepperDriver5160: true,
            serialRxPin:'PD.9',
            serialTxPin:'PD.8',
            espDataReadyPin:'PE.10',
            lpcTfrReadyPin:'PE.12',
            espResetPin:'PE.11',
            lpc: {
                externalSDCard:{
                    csPin: "NoPin",
                    cardDetectPin: "NoPin",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                },
                internalSDCardSPIFrequencyHz: 25000000,
                softwareSPI:{
                    pins: ["NoPin", "NoPin", "NoPin"],
                },
                lcd:{
                    lcdCSPin:       "NoPin",
                    lcdBeepPin:     "NoPin",
                    encoderPinA:    "NoPin",
                    encoderPinB:    "NoPin",
                    encoderPinSw:   "NoPin",
                    lcdDCPin:       "NoPin",
                    panelButtonPin: "NoPin",
                    spiChannel: 2, //Software SPI
                },
                diagnosticPin: "NoPin",
            },
            drives: [
                {
                    diag: "PC.7",
                },
                {
                    diag: "PC.6",
                },
                {
                    diag: "PD.11",
                },
                {
                    diag: "PD.10",
                },
                {
                    diag: "PB.10",
                },
                {
                    diag: "PB.11",
                }
            ],
            auxRX:'PA.10',
            auxTX:'PA.9',
            serialAmount:'2',
            wifi8266CSPin: 'NoPin'
        },
        {
            name: 'biquskr_rrf_e3_1.1',
            type: 'STM32F4',
            caption: 'SKR-RFF-E3-v1.1',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: true,
            microsteppingInterpolation: true,
            numDrives: 4,
            heaterPorts: ['bed', 'e0heat'],
            fanPorts: ['fan0','fan1'],
            pwmPorts: ['bed', 'e0heat','fan0','fan1','neopixel'],
            gpioPorts: ['xstop','ystop','zstop','probe','pson','e0stop','pwrdet'],
            analogPorts: ['bedtemp', 'e0temp'],
            blPorts: ['servo0'],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: true,
            hasESPUpdate: true,
            hasESPOnboard: true,
            hasSBC: false,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: true,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-stm32f4-esp8266wifi',
            firmwareSBCFile: 'firmware-stm32f4-sbc',
            firmwareWifiFile: 'DuetWiFiServer-stm32f4.bin',
            requiresBeta: true,
            iapFile: '',
            expansionBoards: ['BTT E3 RRF IDEX'],
            maxExpansionBoards: 1,
            stepperDriver: "TMC2209",
            stepperDriverTimings: "",
            stepperDriverSmart: true,
            stepperDriver5160: false,
            serialRxPin:'PD.9',
            serialTxPin:'PD.8',
            espDataReadyPin:'PA.6',
            lpcTfrReadyPin:'PA.7',
            espResetPin:'PA.4',
            lpc: {
                externalSDCard:{
                    csPin: "NoPin",
                    cardDetectPin: "NoPin",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                },
                internalSDCardSPIFrequencyHz: 25000000,
                softwareSPI:{
                    pins: ["NoPin", "NoPin", "NoPin"],
                },
                lcd:{
                    lcdCSPin:       "NoPin",
                    lcdBeepPin:     "NoPin",
                    encoderPinA:    "NoPin",
                    encoderPinB:    "NoPin",
                    encoderPinSw:   "NoPin",
                    lcdDCPin:       "NoPin",
                    panelButtonPin: "NoPin",
                    spiChannel: 2, //Software SPI
                },
                diagnosticPin: "PE.2",
            },
            drives: [
                {
                    diag: "PC.0",
                },
                {
                    diag: "PC.1",
                },
                {
                    diag: "PC.2",
                },
                {
                    diag: "PC.3",
                }
            ],
            auxRX:'PA.10',
            auxTX:'PA.9',
            serialAmount:'2',
            wifi8266CSPin: 'NoPin'
        },
        {
            name: 'fly_e3_pro',
            type: 'STM32F4',
            caption: 'Fly-E3-Pro',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: true,
            microsteppingInterpolation: true,
            numDrives: 5,
            heaterPorts: ['bed', 'e0heat', 'e1heat'],
            fanPorts: ['fan0','fan1', 'fan2', 'fan3'],
            pwmPorts: ['bed', 'e0heat', 'e1heat','fan0','fan1', 'fan2', 'fan3','neopixel', 'laser'],
            gpioPorts: ['xstop','ystop','zstop','probe','pson','e0stop', 'e1stop','pwrdet'],
            analogPorts: ['bedtemp', 'e0temp', 'e1temp', 'boardtemp'],
            blPorts: ['servo0'],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: true,
            hasESPUpdate: true,
            hasESPOnboard: true,
            hasSBC: false,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: true,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-stm32f4-esp8266wifi',
            firmwareSBCFile: 'firmware-stm32f4-sbc',
            firmwareWifiFile: 'DuetWiFiServer-stm32f4.bin',
            requiresBeta: true,
            iapFile: '',
            expansionBoards: [],
            maxExpansionBoards: 0,
            stepperDriver: "TMC2209",
            stepperDriverTimings: "",
            stepperDriverSmart: true,
            stepperDriver5160: false,
            serialRxPin:'PD.9',
            serialTxPin:'PD.8',
            espDataReadyPin:'PE.13',
            lpcTfrReadyPin:'PE.14',
            espResetPin:'PE.15',
            lpc: {
                externalSDCard:{
                    csPin: "NoPin",
                    cardDetectPin: "NoPin",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                },
                internalSDCardSPIFrequencyHz: 25000000,
                softwareSPI:{
                    pins: ["NoPin", "NoPin", "NoPin"],
                },
                lcd:{
                    lcdCSPin:       "NoPin",
                    lcdBeepPin:     "NoPin",
                    encoderPinA:    "NoPin",
                    encoderPinB:    "NoPin",
                    encoderPinSw:   "NoPin",
                    lcdDCPin:       "NoPin",
                    panelButtonPin: "NoPin",
                    spiChannel: 2, //Software SPI
                },
                diagnosticPin: "PA.8",
            },
            drives: [
                {
                    diag: "PA.2",
                },
                {
                    diag: "PB.10",
                },
                {
                    diag: "PC.4",
                },
                {
                    diag: "PD.0",
                },
                {
                    diag: "PD.1",
                }
            ],
            auxRX:'PA.10',
            auxTX:'PA.9',
            serialAmount:'2',
            wifi8266CSPin: 'NoPin'
        },
        {
            name: 'biquskr_2',
            type: 'STM32F4',
            caption: 'BTT SKR 2',
            motorWarningCurrent: 1200,
            motorLimitCurrent: 2000,
            seriesResistor: 4700,
            microstepping: true,
            microsteppingInterpolation: true,
            numDrives: 5,
            heaterPorts: ['bed', 'e0heat', 'e1heat'],
            fanPorts: ['fan0','fan1', 'fan2'],
            pwmPorts: ['bed', 'e0heat', 'e1heat','fan0','fan1', 'fan2','neopixel'],
            gpioPorts: ['xstop','ystop','zstop','probe','pson','e0stop', 'e1stop','pwrdet'],
            analogPorts: ['bedtemp', 'e0temp', 'e1temp'],
            blPorts: ['servo0'],
            spiCsPorts: [],
            hasEthernet: false,
            hasWiFi: false,
            hasESP: true,
            hasESPUpdate: true,
            hasESPOnboard: false,
            hasSBC: true,
            hasPowerFailureDetection: false,
            hasMotorLoadDetection: true,
            supportsDisplay: true,
            supports12864: false,
            firmwareStandaloneFile: 'firmware-stm32f4-esp8266wifi',
            firmwareSBCFile: 'firmware-stm32f4-sbc',
            firmwareWifiFile: 'DuetWiFiServer-stm32f4.bin',
            requiresBeta: true,
            iapFile: '',
            expansionBoards: ['BTT EXP-MOT'],
            maxExpansionBoards: 1,
            stepperDriver: "",
            stepperDriverTimings: "",
            stepperDriverSmart: true,
            stepperDriver5160: true,
            serialRxPin:'PD.9',
            serialTxPin:'PD.8',
            espDataReadyPin:'PB.10',
            lpcTfrReadyPin:'PB.11',
            espResetPin:'PE.14',
            lpc: {
                externalSDCard:{
                    csPin: "NoPin",
                    cardDetectPin: "NoPin",
                    spiFrequencyHz: 4000000,
                    spiChannel: 0,
                },
                internalSDCardSPIFrequencyHz: 25000000,
                softwareSPI:{
                    pins: ["NoPin", "NoPin", "NoPin"],
                },
                lcd:{
                    lcdCSPin:       "PE.9",
                    lcdBeepPin:     "PC.5",
                    encoderPinA:    "PE.7",
                    encoderPinB:    "PB.2",
                    encoderPinSw:   "PB.1",
                    lcdDCPin:       "NoPin",
                    panelButtonPin: "NoPin",
                    spiChannel: 4, //Software SPI
                },
                diagnosticPin: "PA.13",
            },
            drives: [
                {
                    diag: "PE.0",
                },
                {
                    diag: "PD.3",
                },
                {
                    diag: "PD.0",
                },
                {
                    diag: "PC.6",
                },
                {
                    diag: "PD.12",
                }
            ],
            auxRX:'PA.10',
            auxTX:'PA.9',
            serialAmount:'2',
            wifi8266CSPin: 'NoPin'
        },
	],

	getBoard(boardType) {
		const boardDefinitions = this.getBoards();
		for (let i in boardDefinitions) {
			if (boardDefinitions[i].name == boardType) {
				return boardDefinitions[i];
			}
		}
		throw 'Invalid board';
	},

	isValidPin(board, pin, canAddress) {
		const pinTypes = ['heaterPorts', 'fanPorts', 'pwmPorts', 'gpioPorts', 'analogPorts', 'spiCsPorts', 'blPorts'];
		return pinTypes.some(function(pinType) {
			return board[pinType].some(function(boardPort) {
				return ((!canAddress && Template.isSamePin(pin, boardPort)) ||
						(canAddress !== undefined && Template.isSamePin(pin, `${canAddress}.${boardPort}`)));
			});
		});
	}
}
